on: [push, pull_request]
name: macos tests
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-12
      - run: |
          git clone https://github.com/tinycthread/tinycthread.git
          cp tinycthread/source/tinycthread.c ./
          cp tinycthread/source/tinycthread.h ./
          cd tests
          make
        env:
          CC: gcc-12
          CXX: g++-12
