on: [push, pull_request]
name: macos tests
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-14
      - run: cd tests && make
