on: [push, pull_request]
name: musl x86_64 tests
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.18
          packages: >
            build-base
      - name: Run tests
        run: |
          uname -m
          git clone https://github.com/tinycthread/tinycthread.git
          cp tinycthread/source/tinycthread.c ./
          cp tinycthread/source/tinycthread.h ./
          cd tests
          make

        shell: alpine.sh {0}
