on: [push, pull_request]
name: Test
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y build-essential
      - run: cd tests && make
